-- Enable Row Level Security (Security best practice)
-- This ensures that even if API keys are exposed, rules control access.

-- 1. CINEMAS Table (Brand information)
CREATE TABLE IF NOT EXISTS cinemas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE, -- 'CGV', '메가박스', '롯데시네마'
    color_code TEXT, -- '#FF0000' for styling badges dynamically
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. EVENTS Table (The main goods info)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_title TEXT NOT NULL, -- "듄: 파트 2" (Renamed from title)
    movie_title TEXT, -- "Dune: Part 2" (New field)
    cinema_id BIGINT REFERENCES cinemas(id), -- Connects to Cinemas table
    goods_type TEXT, -- "TTT", "Original Ticket"
    period TEXT, -- "2024.02.28 ~ 소진 시"
    image_url TEXT,
    locations TEXT[], -- Array of strings for branches ["용산", "영등포"]
    official_url TEXT,
    status TEXT DEFAULT '진행중', -- '진행중', '마감임박', '종료'
    is_visible BOOLEAN DEFAULT FALSE, -- Human-in-the-loop: Default to false until approved
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. MOVIES Table (For future expansion: genres, cast, etc.)
CREATE TABLE IF NOT EXISTS movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL UNIQUE,
    tmdb_id INTEGER, -- For linking with TMDB API later
    poster_path TEXT,
    release_date DATE
);

-- Policies (Row Level Security)
ALTER TABLE cinemas ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- DROP existing policies to reset (in case of re-running)
DROP POLICY IF EXISTS "Public events are viewable by everyone" ON events;
DROP POLICY IF EXISTS "Enable insert for everyone" ON events;
DROP POLICY IF EXISTS "Enable delete for everyone" ON events;
DROP POLICY IF EXISTS "Public cinemas are viewable by everyone" ON cinemas;

-- Allow ANYONE (Public) to READ data
CREATE POLICY "Public events are viewable by everyone" ON events
    FOR SELECT USING (true);

-- MVP: Allow INSERT/DELETE for Admin Page (Since we don't have Auth yet)
-- WARNING: In production, you must restrict this to authenticated users only!
-- Secure Policies: Allow INSERT/UPDATE/DELETE only for authenticated users (Admin)
CREATE POLICY "Enable insert for authenticated users only" ON events FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable delete for authenticated users only" ON events FOR DELETE TO authenticated USING (true);
CREATE POLICY "Enable update for authenticated users only" ON events FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Public cinemas are viewable by everyone" ON cinemas
    FOR SELECT USING (true);

-- SEED DATA (Initial Test Data) - Only run if table is empty
INSERT INTO cinemas (name, color_code)
SELECT 'CGV', 'bg-red-600 text-white'
WHERE NOT EXISTS (SELECT 1 FROM cinemas WHERE name = 'CGV');

INSERT INTO cinemas (name, color_code)
SELECT '메가박스', 'bg-purple-800 text-white'
WHERE NOT EXISTS (SELECT 1 FROM cinemas WHERE name = '메가박스');

INSERT INTO cinemas (name, color_code)
SELECT '롯데시네마', 'bg-red-100 text-red-700 border border-red-200'
WHERE NOT EXISTS (SELECT 1 FROM cinemas WHERE name = '롯데시네마');
